// Code generated by goctl. DO NOT EDIT.
package types

type AuthRequest struct {
	QrCode string `json:"qrCode"`
}

type AuthResponse struct {
	AuthCount  int64 `json:"authCount"`
	AuthExpire int64 `json:"authExpire"`
}

type RegisterRequest struct {
	QrCode    string `json:"qrCode"`
	AuthCount int64  `json:"authCount"`
}

type RegisterResponse struct {
	Id int64 `json:"id"`
}
